server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/heima31
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.56.102
  rabbitmq:
    host: 192.168.56.102
    virtual-host: /leyou
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 40

mybatis:
  type-aliases-package: com.leyou.user.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
ly:
  sms:
    exchangeName: ly.sms.exchange
    routingKey: sms.verify.code